### ISSUE TITLE
(HIGH) viewer misalignment when showing detected edge

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#16]
** see folder 2 of github google drive folder for a screenshot example

The positions of the 'overlay detected edge' function are shifted so that the initial detected edges are within the black cut section, which there is no kymograph data for

**Comment by dougkelly88** [comment]
Bug in version with overlaid scatter points tried as alternative to overlaid line with 0.5 alpha. Reverted, fixed.
