### ISSUE TITLE
(HIGH) Error with export wizard

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#19]
Clicked on data export wizard --> create new --> chose folder --> included stats --> 
It got stuck on the viewer page with the busy sign

The same thing happens when I chose not to include stats.

Export...
Warning: Could not start Excel server for export.
XLSWRITE will attempt to write file in CSV format. 
> In xlswrite at 174
  In viewerMain>exportWizard_Callback at 592
  In gui_mainfcn at 95
  In viewerMain at 42
  In @(hObject,eventdata)viewerMain('exportWizard_Callback',hObject,eventdata,guidata(hObject)) 
Error using xlswrite (line 187)
An error occurred on data export in CSV format.

Error in viewerMain>exportWizard_Callback (line 592)
xlswrite(outputName, [headerLine; data]);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('exportWizard_Callback',hObject,eventdata,guidata(hObject))

Caused by:
    Error using dlmwrite (line 112)
    The input cell array cannot be converted to a matrix.
 
Error while evaluating uimenu Callback

**Comment by clairelbromley** [comment]
oh and I have changed all of the default folders on the viewer.m code to my mac desktop folder

**Comment by clairelbromley** [comment]
"I understand that there is no solution to this problem because Matlab is unable to start Excel on a Mac. Considering that I have a 2014b release this is not conforting. I wonder if writing an .xls file does really need the Excel start or if a file can be produce out of Excel."

**Comment by clairelbromley** [comment]
Perhaps this could be helpful?

xlwrite : Export Data to Excel from Matlab on Mac/Win

http://www.mathworks.com/matlabcentral/fileexchange/37560-xlwrite---export-data-to-excel-from-matlab-on-mac-win

**Comment by dougkelly88** [comment]
Thanks - that's what I suspected. I can play around to export a CSV instead
but it won't be as nice :( x

**Comment by clairelbromley** [comment]
so xlwrite won't work? :(

http://www.macworld.co.uk/how-to/mac/how-run-windows-on-mac-using-vmware-boot-camp-3497251/
I was wondering if I should find out about running windows on my mac...

**Comment by clairelbromley** [comment]
https://support.apple.com/en-gb/HT201468

**Comment by clairelbromley** [comment]
https://softwaregeeks.co.uk/product/windows-10-pro/?gclid=Cj0KEQiAiNi0BRDaobaq3dKJhrwBEiQAyVThzXlzp6Tg_g-ezKOAwyo8pzyu4hVMQx4OAdTRRhcyeA8aAi7e8P8HAQ 

It seems suspiciously cheap... but if getting windows 10 could make things easier, I could try to convince Jon that I should set it up so I have both a mac and a PC. You might have to help me define the argument- but guess it boils down to matlab having more functionality on a PC!
