### ISSUE TITLE
(HIGH PRIORITY) Files crashing matlab viewer: google drive folder number 1

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#2]
<prio:high>

The below error message comes up when uploading files such as: 
240815 E14 C2
240815 E17 C2 etc
** Could it be the case that the viewer isn't used to the embryo number being two digits?
** Additionally- E17C2 has negative x axis, but 240815 E14C2 doesn't 

Date = 240815, Embryo = 14, Cut = 2
Index exceeds matrix dimensions.

Error in viewerMain>listData_Callback (line 155)
cutNumber = s{15};

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in @(hObject,eventdata)viewerMain('listData_Callback',hObject,eventdata,guidata(hObject))

Error while evaluating uicontrol Callback

**Comment by clairelbromley** [comment]
Currently have not been able to open a single two digit embryo number

**Comment by dougkelly88** [comment]
This issue was moved to clairelbromley/ZebrafishKymographing#3
