### ISSUE TITLE
Testing export function after changing to xlwrite function

### ISSUE THREAD

**Issue by dougkelly88** [dougkelly88/ClaireDataAnalysis#20]
Post errors here? Or close if everything works...

**Comment by clairelbromley** [comment]
Export...
Undefined function 'xlwrite' for input arguments of type 'cell'.

Error in viewerMain>xxwrite (line 642)
    xlwrite(varargin);

Error in viewerMain>exportWizard_Callback (line 597)
xxwrite(outputName, [headerLine; data]);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('exportWizard_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uimenu Callback

**Comment by clairelbromley** [comment]
Export...
Error using xlwrite (line 48)
Not enough input arguments.

Error in viewerMain>xxwrite (line 642)
    xlwrite(varargin);

Error in viewerMain>exportWizard_Callback (line 597)
xxwrite(outputName, [headerLine; data]);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('exportWizard_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uimenu Callback

**Comment by dougkelly88** [comment]
For now, try replacing xxwrite on lines 597, 617, 621, 625, 629 with
xlwrite?

**Comment by clairelbromley** [comment]
Now it exports! But excel says that it cannot open the file...

**Comment by clairelbromley** [comment]
It's saved as an xlsx- rather than a CSV(?) file
Also- sorry just realised that I started writing on the wrong thread... sorry for messing up the system :/

**Comment by dougkelly88** [comment]
ah, ok, if you search for xlsx in the code and replace with xls instead,
that should work

**Comment by clairelbromley** [comment]
YEAH! It totally works! 
I don't understand how to update the code on github-so I can send across my code on googledrive, or you can explain how to alter it (just don't want to mess things up!)
