### ISSUE TITLE
Mislabelling of positions either in speed v position plot or on raw data overlay

### ISSUE THREAD

**Issue by dougkelly88** [dougkelly88/ClaireDataAnalysis#27]
Go through data and work out which...

**Comment by clairelbromley** [comment]
@dougkelly88  do you want me to go through the data tomorrow- and look at the movies of the preprocessed data to try to work out whether labelling starts from correct side? This could help determine whether the labelling of positions is correct
(I can explain this in the evening!)

**Comment by clairelbromley** [comment]
I think it will be important to have the position labelling in the correct order reflecting where the laser cut has started from- (with position 0 being the cut at which the laser cut started) as this could affect the speed so will be useful to have a note of
(again- I can explain this evening if unclear)

**Comment by dougkelly88** [comment]
Fixed 214c07858b2cca806914ce26a78cfd5671ce21dd.
