### ISSUE TITLE
Ability to look at which kymographs were chosen previously to be included in the analysis

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#28]
After exporting the data, the viewer can no longer determine which kymographs have been selected for use in the analysis

Would it be possible to use the exported excel data sheet to mark kymographs that were selected? By loading it abit like the metadata?-- or some other way. 

I can put onto googledrive the excel document containing all the chosen data

We can discuss this later :)

**Comment by clairelbromley** [comment]
in the shared 'EXCEL FILES' folder, you will find an xlsx document containing all the chosen kymographs for data from 240815
All the data has been converted to number form, unlike the letter form in the xls document that the data is exported as
I don't know if the fact it's now an xlsx document will be a problem for mac matlab- but the metadata file is also xlsx

**Comment by dougkelly88** [comment]
Note: output from xlwrite (Mac) and xlswrite (windows) is slightly different, so will need to account for this on data import...
