### ISSUE TITLE
Export to excel data not working on latest matlab code

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#29]
Latest code that enables the production of videos does not want to export data

**Comment by clairelbromley** [comment]
Export...
Error using xlwrite (line 93)
The POI library is not loaded in Matlab.
Check that POI jar files are in Matlab Java path!

Error in viewerMain>xxwrite (line 653)
        xlwrite(outName, data);

Error in viewerMain>exportWizard_Callback (line 606)
xxwrite(outputName, [headerLine; data]);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('exportWizard_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uimenu Callback

**Comment by clairelbromley** [comment]
I guess it would be worth seeing if it exports on your laptop- as potentially this is a mac thing
For matlab to work for me, I need the xlswrite files in the same folder as the viewer- but I have copied it as I had it in the older viewer set up (which still works)

**Comment by dougkelly88** [comment]
What version of matlab are you using? Do you definitely only have one version installed at once, or could you be switching between versions?

**Comment by clairelbromley** [comment]
I'm using matlab R2014a at work
Does the code export work well on yours?

**Comment by dougkelly88** [comment]
Yes, but on PC it uses the matlab built in xlswrite function rather than the fix for Mac...

**Comment by clairelbromley** [comment]
I'll check it again tomorrow morning...
Could you tell me how many extra files I should have?

**Comment by dougkelly88** [comment]
Just thinking it would be useful to know what version of the software was the working one... Tomorrow, could you download SourceTree from here: https://blog.sourcetreeapp.com/2014/09/25/sourcetree-for-mac-2-0-released/

You can then add the github repo in SourceTree, choose versions, see graphical representations of different branches etc. It should make life easier in the long run :)

**Comment by dougkelly88** [comment]
I've made changes to the code to make sure that it looks in the correct places for xlwrite.m, and it definitely works on my computer. Can you download the newest version tomorrow and give it a try without copying/moving anything, and let me know if that works?

**Comment by clairelbromley** [comment]
Will do :) is this a separate branch or the master branch
Will also get to grips with that software tomorrow xxx

**Comment by dougkelly88** [comment]
But to answer your question: I have Archive and _MACOSX/Archive folders, with 8 items in the former and 6 in the latter.

**Comment by dougkelly88** [comment]
This is the master branch

**Comment by clairelbromley** [comment]
Could it be to do with how the folder is written for it to look in? i.e. whether it is mac or PC format?
I will look and see tomorrow what the format is in the branch that was working for me

**Comment by clairelbromley** [comment]
I mean whether it uses C:// anywhere in the code?

**Comment by dougkelly88** [comment]
It should only be looking at relative paths, that is, it takes the path of the viewer.m file (which it knows because that's where it's running) and works everything out relative to that

**Comment by dougkelly88** [comment]
Another interesting thing, that I think I probably already know the answer to but would nevertheless be good to confirm, is whether on line ~61-63 of the viewerMain.m code (immediately above addpath(funcPath); it reads

funcPath = [pwd filesep '..'];

-OR- 

dummy = [mfilename('fullpath') '.m'];
currdir = fileparts(dummy);
funcPath = [currdir filesep '..'];

**Comment by dougkelly88** [comment]
(on the version that currently works)

**Comment by clairelbromley** [comment]
ok! I will look through the code tomorrow! :)

**Comment by clairelbromley** [comment]
yeah! You are awesome! The latest viewer totally works! You can export data, select points and view the videos :D :+1:

**Comment by clairelbromley** [comment]
On the old code that worked (incase this is still useful) the code reads:
dummy = [mfilename('fullpath') '.m'];
currdir = fileparts(dummy);
funcPath = [currdir filesep '..'];
addpath(funcPath);

**Comment by clairelbromley** [comment]
i.e. same as the updated Master branch viewer

**Comment by clairelbromley** [comment]
I have got sourcetree- but the help videos I have found are abit useless!
Don't want to mess up the code... so unless I find a useful help video- it would be great to go through it at some point
