### ISSUE TITLE
FYI: Don't close the processed data video before it has finished

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#32]
Warning: The following error was caught while executing 'onCleanup' class
destructor:
Invalid or deleted object. 
> In makeMovieOfProcessedData at 54
  In viewerMain>menuViewMovie_Callback at 978
  In gui_mainfcn at 95
  In viewerMain at 42
  In @(hObject,eventdata)viewerMain('menuViewMovie_Callback',hObject,eventdata,guidata(hObject)) 
Error using capturescreen
Invalid object handle

Error in getframe (line 105)
     x=builtin('capturescreen', varargin{:});

Error in makeMovieOfProcessedData (line 54)
        F(ind) = getframe(ax);

Error in viewerMain>menuViewMovie_Callback (line 978)
handles.movieFrames{ax} = makeMovieOfProcessedData(imFName, metadataFName);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('menuViewMovie_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uimenu Callback

**Comment by clairelbromley** [comment]
Just wanted to make you aware of this!
You can close the issue once you have read it :)

**Comment by clairelbromley** [comment]
NB: although "working" sign was still going around- I could move along the kymograph positions and select the ones to include- so that I had finished that embryo before restarting the viewer

**Comment by dougkelly88** [comment]
Possible alternative method: http://www.mathworks.com/matlabcentral/answers/99925-why-does-the-screensaver-get-captured-when-i-use-getframe-on-a-matlab-figure-window-while-creating-a
