### ISSUE TITLE
Include command error

### ISSUE THREAD

**Issue by dougkelly88** [dougkelly88/ClaireDataAnalysis#37]
Error thrown when include pressed more than twice (include, un-include, re-include):

Error using  & 
Matrix dimensions must agree.

Error in viewerMain>checkIfStored (line 894)
        indices = strcmp(dates{1}, handles.date) &
        strcmp(embryoNs{1}, handles.embryoNumber) & ...

Error in viewerMain>menuInclude_Callback (line 924)
indices = checkIfStored(handles, direction);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('menuInclude_Callback',hObject,eventdata,guidata(hObject))

Error in viewerMain>figure1_WindowKeyPressFcn (line
1101)
    callback(handles.menuInclude, []);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('figure1_WindowKeyPressFcn',hObject,eventdata,guidata(hObject))

 
Error while evaluating figure WindowKeyPressFcn

**Comment by clairelbromley** [comment]
duplicate #33

**Comment by clairelbromley** [comment]
Also- an observation- the first time you decide to include a kymograph you just have to press include once. After the first time, you always have to press include twice to get the highlighting to appear
