### ISSUE TITLE
cmd + M on a mac minimises windows

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#38]
The command + M command on a mac to open the metadata doesn't work. 
Change to a different letter? 
https://support.apple.com/en-gb/HT201236

**Comment by clairelbromley** [comment]
maybe d for data?

**Comment by clairelbromley** [comment]
It doesn't really matter anyway - I'm sure I can click on that button myself!

**Comment by dougkelly88** [comment]
Fixed by commit f4af4cc09f91881888c1d402da7554d1875df895
