### ISSUE TITLE
Change movie naming structure

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#44]
When going to save the movie of preprocessed data, would it be possible to have it save with a more informative file name? e.g. date, embryo number, up or down
Only if it's easy! Otherwise I can just type it myself :)

**Comment by dougkelly88** [comment]
Can you not choose the filename yourself in a dialogue?

**Comment by clairelbromley** [comment]
Yes I can- but I was just wondering if the prewritten file name could be
altered? So then I could just press save...
That's what I meant by I could type it myself easily!
Sorry for any confusion Xx

**Comment by dougkelly88** [comment]
Yup. Let me know what you want it changed to.

**Comment by dougkelly88** [comment]
Needs up/down...
