### ISSUE TITLE
Left is right..!

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#51]
On the viewer, when viewing E7 250815- which you added the fix to as it had negative numbering of kymograph positions, when I press the left arrow the point on the graph moves to the right

**Comment by clairelbromley** [comment]
shared processed data with you in new 'left is right' file on google drive
Too sleepy to think of a more scientific way of saying it! Sorry...

**Comment by clairelbromley** [comment]
Same for 240815 E6C2

**Comment by dougkelly88** [comment]
OK, will think about modifying the implementation. Shouldn't make any
difference to results, just a difference in the order in which things are
stored internally.

**Comment by clairelbromley** [comment]
240815 E6C2
Cut movement goes from bottom to top- and this agrees with the direction of numbering 

![240815 embryo 6 cut 2 speed against cut position upwards](https://cloud.githubusercontent.com/assets/13903697/12713438/9616a582-c8c6-11e5-9d39-5c294d06c660.png)

240815, Embryo 6, Cut 2, Kymograph index along cut = -1 upwards: this is position 15.95
![240815 embryo 6 cut 2 kymograph index along cut -1 upwards](https://cloud.githubusercontent.com/assets/13903697/12713464/ca1a5bf8-c8c6-11e5-888b-a3282d72b3a5.png)

**Comment by clairelbromley** [comment]
![240815 embryo 6 cut 1 5 s pre-cut upwards cropped](https://cloud.githubusercontent.com/assets/13903697/12713549/4c370d8e-c8c7-11e5-8b55-93bfca8a015b.png)

**Comment by clairelbromley** [comment]
![240815 embryo 6 cut 2 5 s pre-cut upwards cropped](https://cloud.githubusercontent.com/assets/13903697/12713574/60010838-c8c7-11e5-851a-c9e90afa1aca.png)

**Comment by clairelbromley** [comment]
So makes sense :) 15.95 has been stored as -1 rather than 16

**Comment by dougkelly88** [comment]
Also this is an example of there being two kymographs overhanging the
(negative) end of the cut, just because of the way the positions are worked
out.

**Comment by clairelbromley** [comment]
So is -0.05 actually off the end of the cut? I was thinking that it might be at 0, but due to a rounding error it's slightly off?
