### ISSUE TITLE
Stats are great- one small thing as an FYI

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#53]
The new stats thing in the best thing ever! Thank you :+1: 
:icecream: 
On the stats for 280815 E1C1 (highlighted in red in the file on google drive) instead of having a number in the stats sheets e.g. JonFiltMedian it says down
![screen shot 2016-02-02 at 08 58 55](https://cloud.githubusercontent.com/assets/13903697/12744326/7dd3d1c8-c98b-11e5-9660-6f2fc22ac26f.png)

I think this may be because there is only one data point for this embryo :/ so just as an FYI more than anything that needs fixing :)

**Comment by dougkelly88** [comment]
Can you send me a screenshot? This case should be dealt with by inserting
an empty cell...

**Comment by clairelbromley** [comment]
It's weird because theres nothing in the fx box at the top of the sheet, but it displays down...

![screen shot 2016-02-02 at 10 02 31](https://cloud.githubusercontent.com/assets/13903697/12745970/226f58ee-c994-11e5-9707-54cfa529f18b.png)

**Comment by dougkelly88** [comment]
Is that not just overflow from the adjacent cell? Double click on the line
between the z and the aa in the column headers to expand column z to fit
the text...

**Comment by clairelbromley** [comment]
Shit... yes it is. I'm such an idiot- sorry!
