### ISSUE TITLE
(HIGH) Attach excel file data to kymographs

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#6]
Get data on excel spreadsheet, such as developmental time point and type of cut, and assign to kymograph files

**Comment by clairelbromley** [comment]
Filter data according to: 
extra column into the excel spreadsheet that I have created to tell the computer whether to take the UP or DOWN kymograph values into account (or BOTH) on a final scatter plot of mean/max values for each embryo

**Comment by dougkelly88** [comment]
TODO: modify to work with new metadata as provided.
