### ISSUE TITLE
Update canny edge filter image

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#67]
Doesn't need to be done before Dylans lab meeting, but before I submit the report, it would be good to have a canny edge filter image with its corresponding kymograph. This would then update a figure as seen on the attached powerpoint slide, to go into the report.
I could also go through and include cases where it detects noise- and show how only including edges that went across the time axis minimised this problem

Additionally, depending on how hard it is, would it be possible to keep the axes consistent? Again really not a pressing issue

![screen shot 2016-02-16 at 10 15 54](https://cloud.githubusercontent.com/assets/13903697/13073394/737f18de-d496-11e5-8cd7-58ba194d6e02.png)

**Comment by clairelbromley** [comment]
For report, will need to find an example of the edge filter where noise has been picked up above the edge?

**Comment by clairelbromley** [comment]
Or a least for thesis(!)- as will show why edge has to extend across the time axis

**Comment by dougkelly88** [comment]
Sent 2016-02-16, can generate again if needs be
