### ISSUE TITLE
Random errors in new branch: new edge finding methods

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#70]
Will cut and paste them as I find them: however, not sure how necessary it is to fix them if this branch isn't going to be used for standard analysis

Error using fit>iFit (line 237)
X, Y and WEIGHTS cannot have NaN values.

Error in fit (line 108)
[fitobj, goodness, output, convmsg] = iFit( xdatain, ydatain, fittypeobj,
...

Error in edgeBasedOnMax (line 46)
    [fres, goodness] = fit(t', d', 'poly1', 'Weights', w);

Error in extractQuantitativeKymographData (line 148)
            edgeBasedOnMax(kym_segment, md, out_file, uO.figHandle)

Error in kymographBase (line 149)
               results = extractQuantitativeKymographData(kymographs,
               curr_metadata, userOptions);

Error in kymographUpDownWrapper (line 3)
    kymographBase(root, false);

**Comment by clairelbromley** [comment]
Attempted to access locs(1); index out of bounds because numel(locs)=0.

Error in edgeBasedOnMax (line 59)
        d(indf) = locs(1) * md.umperpixel;

Error in extractQuantitativeKymographData (line 148)
            edgeBasedOnMax(kym_segment, md, out_file, uO.figHandle)

Error in kymographBase (line 149)
               results = extractQuantitativeKymographData(kymographs,
               curr_metadata, userOptions);


Error in kymographUpDownWrapper (line 3)
    kymographBase(root, false);

**Comment by clairelbromley** [comment]
kym_number: 6
         kym_segment: [50x21 double]
                   t: [18x1 double]
                   d: [18x1 double]
    correct_membrane: [50x21 logical]
         fit_results: [1x1 cfit]
               speed: 0.4713

Attempted to access locs(1); index out of bounds because numel(locs)=0.

Error in edgeBasedOnMax (line 59)
        d(indf) = locs(1) * md.umperpixel;

Error in extractQuantitativeKymographData (line 148)
            edgeBasedOnMax(kym_segment, md, out_file, uO.figHandle)

Error in kymographBase (line 149)
               results = extractQuantitativeKymographData(kymographs,
               curr_metadata, userOptions);


Error in kymographUpDownWrapper (line 4)
    kymographBase(root, true);
 
![screen shot 2016-02-17 at 10 04 43](https://cloud.githubusercontent.com/assets/13903697/13106008/f1a9e050-d55d-11e5-8f53-f488c0c1afae.png)
Point at which matlab stops

**Comment by dougkelly88** [comment]
Not fixed, but unlikely to be used any time soon. Closed.
