### ISSUE TITLE
Overlay showing kymograph coverage

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#74]
In our calculations for 5 pixel width, we thought that there would be a small amount of overlap between the different kymographs, and the areas with which they were calculated over.

![image](https://cloud.githubusercontent.com/assets/13903697/13250173/50be9dbc-da20-11e5-85d7-e6a5629b4c57.png)

However, in this overlay, there is a gap between each of the kymograph widths calculated.

![overlay showing kymograph coverage for cut 2 upwards](https://cloud.githubusercontent.com/assets/13903697/13250122/15cb3efe-da20-11e5-9616-c900aee92ff4.png)

I'm unsure why this is the case... could this be due to the rounding error?

**Comment by dougkelly88** [comment]
Yeah, saw that. Need to check :/ x

**Comment by dougkelly88** [comment]
The error is with the overlay image rather than with the kymograph positioning, which is good news for going ahead and processing data
