### ISSUE TITLE
Error running programme not removing scattered light frames

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#78]
Currently unable to run either kymographBase or KymographUpDownWrapper with the 'userOptions.removeCutFrames = false; ' setting- and following error message appears:
This error does not appear if the removeCutFrames is set to true

Saving overlay images...
Error using image
Too many input arguments.

Error in imagesc (line 39)
    hh = image(varargin{:},'CDataMapping','scaled');

Error in plotAndSaveKymographsSlow (line 103)
        imagesc(xt, yt, squeeze(kymographs(:,:,kpos))', clims);

Error in kymographBase (line 160)
               kymographs = plotAndSaveKymographsSlow(stack, curr_metadata, userOptions);

Error in kymographUpDownWrapper (line 3)
    kymographBase(root, false);

**Comment by dougkelly88** [comment]
I can't reproduce this error - does it happen for lots of different
embryos/cuts, or one in particular? Can you let me know which data it
failed on?

**Comment by clairelbromley** [comment]
Date: 280815, Embryo: 10, cut: 1

block_frames =

     1

Trimming...
Trimming E10 C1 took 0.001077 seconds
Median filtering...
Median filtering E10 C1 took 12.374756 seconds
Building kymographs for 280815, Embryo 10 downwards, cut 1
Saving overlay images...
Error using image
Too many input arguments.

Error in imagesc (line 39)
    hh = image(varargin{:},'CDataMapping','scaled');

Error in plotAndSaveKymographsSlow (line 103)
        imagesc(xt, yt, squeeze(kymographs(:,:,kpos))', clims);

Error in kymographBase (line 160)
               kymographs = plotAndSaveKymographsSlow(stack, curr_metadata, userOptions);


Error in kymographUpDownWrapper (line 3)
    kymographBase(root, false);

**Comment by clairelbromley** [comment]
it happened when I tried several different raw data files

**Comment by clairelbromley** [comment]
280815 is in the process of syncing- ill let you know when its done

**Comment by clairelbromley** [comment]
Also currently running the programme on the raw data in google drive to see if the same error appears

**Comment by clairelbromley** [comment]
Trimming E12 C1 took 0.001598 seconds
Median filtering...
Median filtering E12 C1 took 23.232446 seconds
Building kymographs for 240815, Embryo 12 downwards, cut 1
Saving overlay images...
Error using image
Too many input arguments.

Error in imagesc (line 39)
    hh = image(varargin{:},'CDataMapping','scaled');

Error in plotAndSaveKymographsSlow (line 103)
        imagesc(xt, yt, squeeze(kymographs(:,:,kpos))', clims);

Error in kymographBase (line 160)
               kymographs = plotAndSaveKymographsSlow(stack, curr_metadata, userOptions);


Error in kymographUpDownWrapper (line 3)
    kymographBase(root, false);
