### ISSUE TITLE
Q: Do the basal surface calculations use data that has already has the scattered light removed?

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#82]
Just to check that the basal surface and apical surface retraction speed calculations will both start at the same frame post-cut? As I will be comparing them to each other, so it would be good if they started at the same frame

**Comment by dougkelly88** [comment]
When running the basal method it doesn't import anything from the apical case, but because in both cases the processing steps are the same and are both performed on whole frame, un-pre-processed images, the frames removed should be the same in both cases.

**Comment by dougkelly88** [comment]
In fact, this is not true, since means and standard deviations calculated across image frames will not be the same when images have been zero-padded to account for kymographs generated close to the edges of the original 512x512 image.
