### ISSUE TITLE
Help creating figure

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#87]
So for this cut figure:
![image](https://cloud.githubusercontent.com/assets/13903697/13879326/cd7587b6-ed0e-11e5-844c-56c665380a9e.png)

For B, is it possible to change the font size for the graph axes? So that the numbers are a good size when putting this into a figure?

Could you help me get figures like the below for section C?
![screen shot 2016-03-18 at 13 38 23](https://cloud.githubusercontent.com/assets/13903697/13879348/f5197bba-ed0e-11e5-9cf9-13e03a54564a.png)
Basically the cropped zoomed in file, but without any numbers on (as displayed in the viewer) and with the raw data before processing. 
So basically like the 'pre cut cropped' figures that the code generates (one shown below) but without the numbers labelling the axis, and the kymograph to be overlaid over raw data rather than processed data
![240815 embryo 5 cut 1 5 s pre-cut upwards cropped](https://cloud.githubusercontent.com/assets/13903697/13879471/854ca9dc-ed0f-11e5-84bb-67a7051be005.png)

**Comment by dougkelly88** [comment]
For B,  you can open the .fig version of the relevant data, select the button on the far right of the top toolbar (show plot tools and dock figure): then you can interactively click on and change the appearance of different elements. This obviously only makes sense if you're doing changes on a smallish scale, if necessary it's no problem for me to make a script that'll change the appearance of all the figures of a certain type in a given folder, which might be worthwhile at some point in order that everything is consistent

**Comment by dougkelly88** [comment]
For C, I'll modify the viewer so that you can export the zoomed in figure without numbers as requested

**Comment by clairelbromley** [comment]
used size 28 font for writing and size 30 for numbers :)
